### ISSUE TITLE
Import Bramble into src/editor

### ISSUE THREAD

**Issue by humphd** [humphd/next#10]
Let's import the Bramble editor code into `src/editor` so we can hack on it inline and not have to worry about having it as an external dependency.

**Comment by humphd** [comment]
At first, importing this will be a wholesale import without doing all the extra things I want (e.g., removing dead code, integrating build system with our own, etc.).

The only thing I think we should do is pull all submodules into our code and **not** use submodules at all.

**Comment by Fatehsandhu** [comment]
@humphd Shouldn't this one be close? 
https://github.com/humphd/next/pull/33

**Comment by humphd** [comment]
@Fatehsandhu no, since we didn't land #33, we closed it until @twigz20 gets the prettier stuff right.

**Comment by twigz20** [comment]
Just a quick update, I'm pretty far into this but I've hit a bug with prettier and precise-commits. However, I've filed a bug [upstream](https://github.com/nrwl/precise-commits/issues/16) and I'm waiting to hear back.
