### ISSUE TITLE
Fix docs siteConfig.js so you can work locally or on gh-pages

### ISSUE THREAD

**Issue by humphd** [humphd/next#105]
<img width="1457" alt="screen shot 2018-06-18 at 6 17 19 pm" src="https://user-images.githubusercontent.com/427398/41565236-e58fc454-7323-11e8-9eff-8b12ef3ba4f7.png">

@mmBabol I thought you fixed this?  Can you look into what is happening here?

**Comment by mmBabol** [comment]
This is happening because the `url` and `baseUrl` inside of `siteConfig.js` are set to `https://humphd.github.io` and `/next/`. These are set for the deploy step. Is there a way for me to check whether this is being built on the local server or not? That way I could fix this problem.

**Comment by humphd** [comment]
Hm.  It kind of sucks that it's broken for local dev.  However, all of our stuff is pretty broken for local dev at the moment.  So let's morph this into making the docs work locally *and* on gh-pages.

**Comment by mmBabol** [comment]
I think I know how to fix this issue, Ill do a PR shortly to fix this issue

**Comment by humphd** [comment]
Fixed
