### ISSUE TITLE
Create a ServiceWorker with stubs for all routes in README

### ISSUE THREAD

**Issue by humphd** [humphd/next#11]
We need a ServiceWorker, probably based on https://developers.google.com/web/tools/workbox/, to handle all the routes defined in https://github.com/humphd/next#routes.  For now they can simple stubs that just return static content or data.

**Comment by Fatehsandhu** [comment]
@humphd Can we close this since it was addressed in the PR#41?

**Comment by humphd** [comment]
Yes, this is basically done now.  Any follow-up routes we need at this point can be done in new PRs/bugs.
