### ISSUE TITLE
Error while running the terminal on Safari.

### ISSUE THREAD

**Issue by Fatehsandhu** [humphd/next#116]
Terminal not loading on safari. Works on chrome.
```
TypeError: undefined is not an object (evaluating 'this.node_treble_left.connect(this.node_bass_left).connect')
```

**Comment by humphd** [comment]
Filed upstream in https://github.com/copy/v86/issues/216

**Comment by humphd** [comment]
[Fixed upstream](https://github.com/copy/v86/pull/218), and I've rebased my stuff to work with the fix.  To get my fix:

```
rm -fr node_modules/v86
npm install
```

Safari is really, really slow to boot for some reason.
