### ISSUE TITLE
TravisCI integration and Deployment

### ISSUE THREAD

**Issue by humphd** [humphd/next#14]
We need automatic testing and deploy to gh-pages using TravisCI.

**Comment by humphd** [comment]
Needs to be done on `travis-ci.com` based on https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by SeanPrashad** [comment]
[GitHub checks](https://help.github.com/articles/about-status-checks/#checks) is in beta but it might be something of interest. It's currently only available for [TravisCI](https://github.com/marketplace/travis-ci) and [AppCenter](https://github.com/marketplace/app-center).

**Comment by humphd** [comment]
I'll do the bits of this that require account stuff in Travis/GitHub, and @dsych is going to do the rest.  Our first goal is to get automatic deployment on gh-pages.
