### ISSUE TITLE
using `next` in an educational context (in a distant future)

### ISSUE THREAD

**Issue by titaniumbones** [humphd/next#140]
Hi @humphd,
I just happened on this repo as I was exploring outwards from Thimble & Bramble.  I teach digital humanities at U of T, so right in your back yard, and I am currently spending a lot of time thinking about how to [simplify coding environments for my students](https://hackmd.io/yLrbdaW4QMmy2LIgq3BllQ?both#). I wondered to what extent you are thinking of `next` as a pedagogical environment? 

I am simultaneously [starting another project teaching web skills to kids in rural India](https://hackmd.io/Ci5kwXOoTLSFabpThfuuBg?both#). Some of the features I see in the issues list are potentially of interest for this use case (offline environment, etc). I would be very grateful for a chance to talk it over with you if yyou have some time.  

GH issues are maybe a funny place for htis kind of inquiry but, well, thought I might as well!

**Comment by humphd** [comment]
Hey @titaniumbones, happy to talk about this in email if you want, david.humphrey@senecacollege.ca.
