### ISSUE TITLE
Evaluate using real emulated shell instead of writing one from scratch

### ISSUE THREAD

**Issue by humphd** [humphd/next#26]
Before we go too far down the road of creating our own [command line shell](https://github.com/humphd/next#command-line-shell), I think it would be wise to figure out whether or not we can adapt one of the existing emulated OS/shell projects that use emscripten/asm.js.  There are a few I'm aware of, listed here in perceived order of activity (there are also some others I think are dead, and I didn't list):

* [v86](https://github.com/copy/v86)
* [jor1K](https://github.com/s-macke/jor1k)
* [JSLinux](https://bellard.org/jslinux/)

It looks to me like all or most of these use some minimal Linux kernel/bootloader + [BusyBox](https://busybox.net/about.html) to give a shell (`ash`) and the usual Unix commands one would expect.  The list of commands can be [further stripped down via configure options](https://busybox.net/FAQ.html#optimize) to reduce size even more.  For our uses case (i.e., supporting working with files), lots of things aren't necessary (e.g., networking).

An open question I have is how one would go about sharing the filesystem with other JS running on the same domain.  Most of the current examples I've seen are focused on using files in RAM or on the server vs. hosting something in browser storage.  It looks to me like this should be possible, though, but I don't fully understand it yet.

Another thing I think would be cool is somehow leveraging our Service Worker to keep a process alive and/or suspend and resume vs. having to do cold startup all the time.  I did come across the [em-shell](https://github.com/tbfleming/em-shell) project, which sort of does this.  It also uses an [emscripten-compiled busybox](https://github.com/tbfleming/em-busybox).

My gut tells me this is all doable.  Since we don't care about performance as such (i.e., we're not trying to run huge apps in the emulator), the question is: can we get the filesystem to be shared between the editor, Service Worker, and this terminal?  And, can we do it with enough performance (startup time, download size) to be workable beyond being a cool demo.

**Comment by humphd** [comment]
I reached out to the authors of v86 and jor1k to see if they had an thoughts or suggestions, and whether or not they wanted us to contribute upstream.  I'll update this bug if I hear back.

In the meantime, I've been playing with different disk images on v86.  The [BG-Tiny Linux BootDisk](http://www.giannone.ch/bgtlb/current/#FAQ) is a Linux on a Floppy distribution that fits in 1.4M.  It only needs 4M of RAM to run, and works really well.

This approach of using a floppy bootdisk approach might work well.  We should be able to make our own with something like [Buildroot](https://buildroot.org/).  I want to explore and test some other options, and also try and get the same thing working in jor1k.

**Comment by copy** [comment]
Yes, this should be possible. The [file system implementation](https://github.com/copy/v86/blob/master/lib/filesystem.js) in v86 is a simple in-memory file system that takes a json file produced by [fs2json](https://github.com/copy/fs2json) which contains the entire directory tree and file attributes. The file contents are loaded on-demand from a webserver using xhr. jor1k uses the same [file system](https://github.com/s-macke/jor1k/blob/master/js/worker/filesystem/filesystem.js) (but a slightly different loading strategy).

I think the easiest way to implement your idea would be to extend filesystem.js to have something akin to mount points, e.g. certain directory tree are attached to different backends. One of those backends could then be connected to your existing in-browser storage, while another could be a read-only snapshot of a busybox distribution that is loaded on-demand or all at once.

It is also possible to have multiple virtio-9p devices and mount them in separate directories in Linux. They are identified by a mount tag, which is currently [hard-coded](https://github.com/copy/v86/blob/5eb5389e52aaae7cd9fa4d1445d9f447fed7fc7c/lib/9p.js#L68) in v86.

**Comment by humphd** [comment]
@copy thanks for adding some notes to this.  It helps a lot to hear that you think this is doable.  I'm going to do some experiments in the next few weeks to see if I can get my filesystem hacked into yours somehow.  It sounds like your FS must already be async, if you're doing XHR to get file contents, which is good, since mine also needs to be async for IndexedDB calls.

I have a lot of questions, but let me do some research to see how many I can answer on my own without wasting your time.  I'll report back on what I find, and any problems I hit.

**Comment by humphd** [comment]
Another colleague suggested https://browsix.org/, but I think it looks a) abandoned; b) lacking a bunch of things that you end up getting "for free" with the full VM approach.

**Comment by humphd** [comment]
Here's a screenshot:

<img width="1175" alt="screen shot 2018-05-29 at 2 47 42 pm" src="https://user-images.githubusercontent.com/427398/40679379-f76c15ca-6350-11e8-8da7-64cd72eb2929.png">

**Comment by humphd** [comment]
This is going to work https://twitter.com/humphd/status/1007720404818059264.  Closing and I'll follow more bugs upstream and here as we hit things.
