### ISSUE TITLE
Travis Deploy Failing on Master

### ISSUE THREAD

**Issue by twigz20** [humphd/next#38]
I pushed #36 and noticed that the deploy failed [invalid option "--github-token="](https://travis-ci.com/humphd/next/jobs/124835467#L1272).

**Comment by Fatehsandhu** [comment]
The settings are specific to each repository. If you don't set them in https://travis-ci.org/superflycss/component-header/settings, they're not available to your builds in superflycss/component-header.

**Comment by Fatehsandhu** [comment]
@twigz20 I restarted the build and it passed, must have been a random error.
