### ISSUE TITLE
Consider issue and pull request templates

### ISSUE THREAD

**Issue by SeanPrashad** [humphd/next#4]
A problem that maintainers face is the lack of detail in issues and pull requests which often results in extraneous discussion.

We should formulate an agreed upon issue and pull request template to solve this problem.

Consider the following resources:

1. [devspace/awesome-github-templates](https://github.com/devspace/awesome-github-templates)
2. [stevemao/github-issue-templates](https://github.com/stevemao/github-issue-templates)

**Comment by humphd** [comment]
I'm going to suggest we go a different way.  As you mention, lots of projects favour clean process over the mess of dealing with new people who don't know all the rules, processes, and customs of the project.  I'd like to flip this, and try, as much as possible, to engage in "extraneous discussion," allow support style issues, and generally get people involved without the burden of having them adhere to our bureaucracy.

For now, I'm going to close this and see what happens.  If I'm wrong and we can't handle the influx of people, we'll return to it.  Thanks for suggesting this, even though I want to see us go a different direction.
