### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by dsych** [humphd/next#50]
Whenever I navigate to our [docs](https://humphd.github.io/next/), it does not load images.

![docs_broken](https://user-images.githubusercontent.com/16144679/40334434-d365c73c-5d2b-11e8-8662-40338120c878.png)

**Comment by dsych** [comment]
@mmBabol can you verify why this is happening?

**Comment by mmBabol** [comment]
@dsych Looking into it. The images/css file is being linked incorrectly
