### ISSUE TITLE
Use Prettier from day 1 for automatic code formatting

### ISSUE THREAD

**Issue by humphd** [humphd/next#7]
Let's use [Prettier](https://prettier.io) to format all of our code.  See https://prettier.io/docs/en/precommit.html for info on how to set this up so it runs automatically.

**Comment by humphd** [comment]
For me, the only things I care about are:

* semicolons please!
* spaces (2 or 4 is fine)

https://github.com/facebook/react/blob/master/.prettierrc.js is what Facebook is doing on react.

**Comment by dsych** [comment]
Useful [extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) for VSCode that can consume prettier.rc file.

**Comment by dsych** [comment]
@humphd trying to only format modified parts of the files to avoid giant PRs. I am using [precise-commits](https://github.com/nrwl/precise-commits) to achieve this, and it seems like we can not only format the code on commits, but check the formatting in the CI. So far I ran into a [problem](https://github.com/nrwl/precise-commits/issues/2) with partially formatting json files. I am thinking about excluding json files for the time being.

**Comment by mmBabol** [comment]
Bug fixed with PR #29
