### ISSUE TITLE
Use Eslint

### ISSUE THREAD

**Issue by humphd** [humphd/next#8]
In combination with #7, let's use [eslint](https://eslint.org/docs/user-guide/getting-started) to automatically find and fix issues in our code.

**Comment by SeanPrashad** [comment]
A list of different eslint configurations can be found [here](https://github.com/dustinspecker/awesome-eslint#configs). We could possibly use one as a base configuration and adjust to our liking.

**Comment by Fatehsandhu** [comment]
@humphd Can I work on this one by any chance?
