### ISSUE TITLE
Run eslint when we run tests

### ISSUE THREAD

**Issue by humphd** [humphd/next#86]
In #84 we added eslint+prettier to auto-format our code.  Let's add a `pretest` script that does `npm run eslint` so we get this for free when we run tests.

**Comment by SeanPrashad** [comment]
I'd be happy to get this one across the finish line in the next few days!

**Comment by humphd** [comment]
@SeanPrashad great, if you want to do this, here's what I'd suggest:

* Add another `npm script` named `check-eslint` that runs eslint but doesn't use `--fix`.
* Add another `npm script` named `travis` that calls `npm run test`, and then add `pretravis` that does `npm run check-eslint`
* Fix our `.travis.yml` to get rid of https://github.com/humphd/next/blob/master/.travis.yml#L22-L25 and add a `script:` that does `npm run travis`
