### ISSUE TITLE
Switch workbox cache strategy

### ISSUE THREAD

**Issue by humphd** [humphd/next#94]
We've been using `CacheFirst` a lot, and it's nice because it's fast; but when the underlying resource is changing a lot, it's annoying because you have to clear your cache to get updated content.

Let's switch to [Stale While Revalidate](https://developers.google.com/web/tools/workbox/modules/workbox-strategies#stale-while-revalidate) so it uses cache, but also updates what's in the cache so the next request is up-to-date.

**Comment by Fatehsandhu** [comment]
@humphd @dsych already addressed this issue. Can it be closed?

**Comment by humphd** [comment]
No, we still need to do this everywhere.  I haven't done this yet.

**Comment by dsych** [comment]
This is supposed to be done in incoming PRs. Main codebase is already `stalewhilerevalidate`
